### ISSUE TITLE
`#[tracker::track]` fails when struct has generic attributes

### ISSUE THREAD

**Issue by mskorkowski** [AaronErhardt/Tracker#2]
While migrating components so they can be reused I've hit a problem in tracker where structs will fail to compile if they have generic attribute.

This fails to compile

```
#[tracker::track]
/// Model of the save dialog component
pub struct SaveDialogModel<Config: SaveDialogConfig> {
    #[do_not_track]
    _config_provider: PhantomData<*const Config> //we don't own Conf, there is no instance of Conf
}
```

Removing tracker macros makes it compile.

**Comment by AaronErhardt** [comment]
The issue should now be fixed.
