### ISSUE TITLE
error: defaults for type parameters are only allowed in `struct`, `enum`, `type`, or `trait` definitions

### ISSUE THREAD

**Issue by mskorkowski** [AaronErhardt/Tracker#3]
If struct has a default parameter for a type then tracker passes default value to the impl section

In pagination component for the data store I wrote

```rust
#[tracker::track]
#[derive(Debug)]
pub struct PaginationViewModel<Config, Allocator=DefaultIdAllocator> 
where 
    Config: PaginationConfiguration<Allocator> + 'static,
    Allocator: TemporaryIdAllocator + 'static,
{
    #[do_not_track]
    view: Rc<RefCell<StoreViewImplementation<Config::ParentWidgets, Config::ParentViewModel, Config::ParentComponents, Allocator>>>,
    page: gtk::EntryBuffer,
    pages_total: String,
}
```

which is expanded to 

```rust
pub struct PaginationViewModel<Config, Allocator = DefaultIdAllocator>
    where
        Config: PaginationConfiguration<Allocator> + 'static,
        Allocator: TemporaryIdAllocator + 'static,
{
    view: Rc<
        RefCell<
            StoreViewImplementation<
                Config::ParentWidgets,
                Config::ParentViewModel,
                Config::ParentComponents,
                Allocator,
            >,
        >,
    >,
    page: gtk::EntryBuffer,
    pages_total: String,
    tracker: u8,
}

impl<Config, Allocator = DefaultIdAllocator> PaginationViewModel<Config, Allocator> {
    ...
}
```

**Comment by AaronErhardt** [comment]
Thanks for pointing this out. If I understand this correctly (I have never used this kind of syntax before) the last section should be just
```rust
impl<Config> PaginationViewModel<Config> {
    ...
}
```

Or is the allocator type needed for the `impl`?

**Comment by mskorkowski** [comment]
Nope last section should be: 

```
impl<Config, Allocator> PaginationViewModel<Config, Allocator> 
where
    Config: PaginationConfiguration<Allocator> + 'static,
    Allocator: TemporaryIdAllocator + 'static,
{
    ...
}```

**Comment by AaronErhardt** [comment]
I've added a patch. Can you test the new version from the git repository? If you're successful I'll create a new release.

**Comment by mskorkowski** [comment]
It's still failing. Also test case you provided is failing.

**Comment by AaronErhardt** [comment]
The thing that confuses me the most is that the CI is failing while it's compiling just fine on my PC, even though I'm using stable as well...

**Comment by mskorkowski** [comment]
Have you tried to use `cargo exapnd` to check how the file looks like after the macros has been applied? It helped me a ton

**Comment by AaronErhardt** [comment]
With cargo expand I get:
```rust
    struct TestDefaultParam<Config, Allocator = NoCopy> {
        _config: std::marker::PhantomData<Config>,
        _allocator: std::marker::PhantomData<Allocator>,
        tracker: u8,
    }
    impl<Config, Allocator> TestDefaultParam<Config, Allocator> {
        ...
    }
```

from 
```rust
    #[crate::track]
    struct TestDefaultParam<Config, Allocator = NoCopy> {
        _config: std::marker::PhantomData<Config>,
        _allocator: std::marker::PhantomData<Allocator>,
    }
```

Looks about right to me. And as I said the test passes perfectly fine on my PC just not during the CI...

**Comment by mskorkowski** [comment]
I'll try to dig it tomorrow. Today, I'll swap to watch! to make a pagination component work fully

**Comment by AaronErhardt** [comment]
Fixed it now, I think. I forgot that the macro lives in its own crate and the tracker crate pulled the old macro from crates.io. It's published now so `cargo update` should do the job, even without the git repo as dependency.

**Comment by mskorkowski** [comment]
Macro is skiping `where` section. 

I can work around it by moving where section into the parameters like this

```rust
pub struct PaginationViewModel<Config: PaginationConfiguration<Allocator> + 'static, Allocator: TemporaryIdAllocator + 'static =DefaultIdAllocator> 
```

But there are cases where this might not be enough when there are dependent types involved.

```rust
where
    Config::A: TraitB
```

**Comment by mskorkowski** [comment]
I've tested the behavior together with workarounds from my previous post and it works. 👍🏻 

I would say keeping where section would be the next step to make it 💯

**Comment by AaronErhardt** [comment]
`where` should work properly now :)
