### ISSUE TITLE
Update function uses Fn

### ISSUE THREAD

**Issue by N4tus** [AaronErhardt/Tracker#5]
The generated update function uses the `Fn` trait to specify its parameter. This prevents moving values from the update-closure during updating of the tracked value. Using `FnOnce` would be more appropriated and allows for moving captured values:
```rust
#[tracker::track]
struct Model {
   #[tracker::no_eq]
   names: Vec<String>
}

fn main() {
   let mut model = Model {
      names: vec!["Alpha".to_string(), "Beta".to_string()],
      tracker: 0,
   };
   
   let new_name = "Gamma".to_string();
   model.update_names(move |names|{
      names.push(new_name); // Cannot move captured value in Fn closure. Using FnOnce would allow this.
   });
}
```

**Comment by AaronErhardt** [comment]
Thanks for pointing this out! Do you want to submit a PR?

**Comment by N4tus** [comment]
I have made a PR (#6) with that change. I've been using it in a local project and it seems to work, but I haven't done extensive testing.

**Comment by AaronErhardt** [comment]
Sorry that it took so long, but now a new version (that includes your PR) is out on crates.io!

I think I can close this issue now.
